---
output: 
    stevetemplates::cv
geometry: margin=1in

title: "Cover Letter"
author: Miles D. Williams

jobtitle: Department of Political Science, University of Illinois at Urbana-Champaign
address: "David Kinley Hall · 1470 W Gregory Drive · Urbana IL, 61801"
email: "milesdw2@illinois.edu"
# github: "milesdwilliams15"
phone: "618-663-9499"
web: "milesdwilliams15.github.io"
fontawesome: yes
updated: false

fontfamily: cochineal
fontsize: 12pt
linkcolor: blue
urlcolor: blue
---


\bigskip

Dear Search Committee Members,

\bigskip

I am writing this letter to express my interest in the [International Relations?] position posted by your department. I am a doctoral candidate in the Department of Political Science at the University of Illinois, and I expect to defend my dissertation by June 2022 under the supervision of Matt Winters, Xinyuan Dai, Bob Pahre, and Rob Carroll. 

My primary research agenda centers on the political economy of foreign aid. I have special interest in identifying the foreign policy goals countries pursue through their aid allocation and in explaining the strategic responses among leading foreign aid donors to each other as they allocate aid to developing countries. To address these issues, I rely on various tools, from formal theory to machine learning, as well as classical econometric techniques.

In my dissertation, I study the issue of strategic interactions among bilateral aid donors. I begin from the assumption that leading industrialized countries target economic assistance to developing countries in order to maximize wide-ranging foreign policy interests. But, as they do so, the aid allocated by one produces a mix of positive and negative foreign policy externalities for all others, and vice versa. Analyzing a formal model, I am able to deduce best-responses among aid donors, and the welfare implications of these best-responses. I find that the most likely outcome in equilibrium is inefficient competitive waste. Donors direct more of their aid budgets to recipients where rivalry is most pronounced and away from recipients where they share more common interests. If they could agree to cooperate, a more efficient solution would entail mutually diverting some aid away from recipients that are sites of rival foreign policy gains and to recipients that are sites of mutual interest. 

I subsequently put the empirical implications of this model to the test. In doing so, I make a novel contribution to measurement by developing two composite measures that (1) capture leading countries' foreign policy interests with respect to individual developing countries and (2) capture individual developing countries' relative need for economic assistance. Using a mix of machine learning and conventional econometric techniques, I recover evidence, not only that leading donor countries engage in strategic responses to one another as they allocate aid but also that their responses are conditioned by their foreign policy interests and by recipient need. This suggests that the foreign policy externalities generated through aid giving are determined by the salience of donors' foreign policy interests and by the relative need recipients have for aid. Using the aggregate interests of other donors as an instrument, I additionally find that donor responsiveness is most prevalent within the neediest recipients. Further, among these recipients, a donor responds competitively to peer aid where its foreign policy interests are strongest and deferentially to peer aid where its interests are minimal. These findings shed new light on strategic responses among aid donors by revealing not only that donors strategically target their aid based on the giving of others but also by identifying *when* and *where* these responses are competitive or deferential. 

Beyond my dissertation, I also maintain a research agenda focused on the determinants and impacts of aid allocation broadly construed. In one paper I was invited to revise and resubmit to *International Studies Quarterly*, I examine how donor interests in supporting bilateral trade and minimizing unwanted migration influence how they differently target economic assistance in developing countries experiencing civil war and those at peace. In another work-in-progress in collaboration with Lucie Lu (University of Illinois), we explore the intersection of aid allocation and media coverage of aid recipients in the context of China's foreign aid program. In this project we rely on the Archer web application recently developed by the Cline Center for Advanced Social Research to collect data on *Xinhua* news articles that mention countries that receive foreign aid from China. We merge country mentions and article sentiment data with information on Chinese bilateral aid allocations compiled by AidData to assess whether coverage of recipients in Chinese media influence where officials target aid or whether China's aid allocations dictate coverage of aid recipients. We plan to have a manuscript ready for submission to a journal by the beginning of the Spring semester.

I further have an interest in the politics of multilateral development institutions. I recently coauthored a chapter on the history of and issues related to the World Bank with Matt Winters for the *Handbook of International Organizations: Theories, Concepts and Empirical Insights*. I also have a working paper that explores theoretically and empirically the tension besetting institutions like the World Bank to bend to the interests of their most influential donors versus targeting their loan and grant allocations to the most deserving recipients.

In a pair of papers coauthored with Ryan Burge at Eastern Illinois University, I use text-as-data methods to understand political communication in the domain of religion. In an article published in the *Journal of Communication and Religion*, we applied a combination of natural language processing, descriptive analysis, and sentiment analysis to shed new light on the differential political communications of clergy in their sermons on the basis of gender. In another article published in the *Journal of Religion, Media, and Digital Culture*, we explored a novel dataset of Tweets made by more than 80 prominent Protestant Evangelical leaders with an eye to the most common themes in their communications and to their messaging on political issues.

Methodologically, I maintain a research agenda centered on developing new methods for identifying causal estimates with observational data. In one ongoing project, I propose a novel application of random forests to the problem of regression adjustment. In addition to developing an R package for implementing this approach to regression adjustment, I detail the method in a manuscript that I will place under review this semester. In another project, I build upon an existing model-based approach to estimating a "strategic autoregressive model" (StratAM) and currently have a related R package under development for implementing the method.

Professionally, I further have honed my expertise in design-based inference and quasi-experimental designs in my time serving as an Associate Fellow on the Methods Team at the U.S. Office of Evaluation Sciences (OES). OES is a federal agency that relies on a team of interdisciplinary experts to help other federal agencies build and use evidence. In my role on the Methods Team, I consult on the development of research designs, support quality control for OES projects by conducting blind reanalyses for evaluations conducted by other team members, and contribute to the development of guidance documents and data visualization tools for OES. I have supported rapid evaluation of pandemic relief for small businesses, taking the lead in obtaining, cleaning, and merging millions of rows of credit card transaction data from a leading vendor with administrative data on small businesses that applied for pandemic assistance from major cities. I additionally contributed to descriptive analyses and data visualizations used to present results to stakeholders in cities and in the Small Business Administration.

My time at Illinois has prepared me to teach courses in international relations, international political economy, data analysis, and formal theory. I would be especially interested in teaching a course on the politics of foreign aid and development. At Illinois, I have facilitated discussion sections in Intro to Political Science, and have instructed an online Intro to International Relations course. In my teaching, I promote rigor and expect a strong work-ethic and engagement from my students.

I am also eager to serve as a contributing member to the life and work of your department. At Illinois I have taken on various roles. I have served on, and been interim head of, the graduate Methods Committee. I have also volunteered for four years as an instructor for a yearly Math Camp the political science department holds for incoming graduate students, teaching crash-course sessions on probability and distributions in R, calculus, and linear regression. I also serve as the organizer for an International Relations workshop, which provides graduate students at Illinois an opportunity to share their ongoing research with peers and faculty members to receive feedback and strengthen their work.

I believe my experience and qualifications will make me a valuable addition to the life, research, and teaching of your department. Please find the package of application materials that I have included with this letter. You can email or call me any time with questions.

\bigskip

Sincerely,

Miles D. Williams

\vspace{-10pt}

Ph.D. Candidate

\vspace{-10pt}

Department of Political Science

\vspace{-10pt}

University of Illinois at Urbana-Champaign