---
output: 
    stevetemplates::cv
geometry: margin=1in

title: "Cover Letter"
author: Miles D. Williams

jobtitle: Department of Political Science, University of Illinois at Urbana-Champaign
address: "David Kinley Hall · 1470 W Gregory Drive · Urbana IL, 61801"
email: "milesdw2@illinois.edu"
# github: "milesdwilliams15"
phone: "618-663-9499"
web: "milesdwilliams15.github.io"
fontawesome: yes
updated: false

fontfamily: cochineal
fontsize: 12pt
linkcolor: blue
urlcolor: blue
---

\bigskip

To Dr. Randall Stone,

\bigskip

I am writing this letter to express my interest in the Post-Doctoral Fellowship at the University of Rochester's Skalny Center for the 2022-23 academic year. I am a doctoral candidate in the Department of Political Science at the University of Illinois, and I expect to defend my dissertation by June 2022 under the supervision of Matt Winters, Xinyuan Dai, Bob Pahre, and Rob Carroll. 

I have broad training in international relations with a specialization in international political economy. My primary research agenda centers on the political economy of foreign aid. I have special interest in identifying the foreign policy goals countries pursue through their aid allocation and in explaining the strategic responses among leading foreign aid donors to each other as they allocate aid to developing countries. To address these issues, I rely on various tools, from formal theory to machine learning, as well as classical econometric techniques.

In my dissertation, I study the issue of strategic interactions among bilateral aid donors. I begin from the assumption that leading industrialized countries target economic assistance to developing countries in order to maximize wide-ranging foreign policy interests. But, as they do so, the aid allocated by one produces a mix of positive and negative foreign policy externalities for all others, and vice versa. 

The first chapter of my dissertation is dedicated to analyzing a game-theoretic model of a political economy of aid. With this model, I gain greater insight into a timely question in international development: *why do donor governments struggle to collaborate in the distribution of foreign aid to developing countries?* Implicit in this question is the presumption that collective provision of aid yields mutual foreign policy gains for donors. However, analysis of the model demonstrates that collective solutions do not always Pareto improve on individual best-responses. The most likely outcome in equilibrium is inefficient competitive waste. Donors direct more of their aid budgets to recipients where rivalry is most pronounced and away from recipients where they share more common interests. In many equilibria, this outcome is Pareto inefficient and donors would mutually benefit if they would commit to a collectively optimal distribution of aid. However, there exists a sizable set of equilibria where the choice between individual and collective optimization can lead to conflicting payoffs between donors. While one donor may do much better under a collective solution, the other will do worse. This highlights a potential source of friction that may explain the stunted progress in donor collaboration to-date.

The model further helps to underline a limitation of many previous empirical analyses of donor responses. Much prior work attempts to infer from the average direction of donor responses whether they are competitors for rival foreign policy gains or free-loaders who pass the buck when other donors are willing to foot the bill for development projects. But, analysis of the model demonstrates many instances where complementarity or substitution follow from a mix of common or rival goals and different marginal utilities for achieving goals in recipients. Only when comparing donor responses in recipients where a donor has similar goals (rival or common) is it possible to draw inferences about the mechanism driving a donor's reaction to peer aid. This is an insight that informs the empirical analysis I take up in a subsequent chapter of my dissertation.

The remainder of my dissertation deals with empirically identifying *when* and *where* donor governments compete for rival foreign policy gains through aid allocation or pass the buck to others. In doing so, I make a novel contribution to measurement by developing two composite measures that (1) capture leading countries' foreign policy interests with respect to individual developing countries and (2) capture individual developing countries' relative need for economic assistance. Next, using a mix of machine learning and conventional econometric techniques, I recover evidence, not only that leading donor countries engage in strategic responses to one another as they allocate aid but also that their responses are conditioned by their foreign policy interests and by recipient need. Specifically, I find that donor responsiveness is most prevalent within the neediest recipients. Further, among these recipients, donors respond competitively to peer aid where their foreign policy interests are strongest and deferentially to peer aid where their interests are minimal. These findings shed new light on strategic responses among aid donors by revealing not only that donors strategically target their aid based on the giving of others but also by identifying *when* and *where* they compete and pass the buck.

In the final chapter of my dissertation I turn to consider the implications of donor interactions for the emergence of "lead donorship," a condition of single donor dominance in relationship with an aid recipient that is purported to have normative implications for aid effectiveness. I find that lead donorship emerges just where the previous set of empirical findings would predict: a donor is most likely to have lead donor status in high need recipients where the donor has much stronger foreign policy interests than other donors. By better understanding the strategic factors that determine lead donorship it is possible to consider its import for development outcomes in recipient countries.

Beyond my dissertation, I maintain a research agenda focused on the determinants and impacts of aid allocation more broadly. In one paper I was invited to revise and resubmit to *International Studies Quarterly*, I examine how donor interests in supporting bilateral trade, minimizing unwanted migration, and helping a strategically valuable country influence how they differently target economic assistance in developing countries experiencing civil war and those at peace. In another work-in-progress in collaboration with Lucie Lu (University of Illinois), we explore the intersection of aid allocation and media coverage of aid recipients in the context of China's foreign aid program. In this project we rely on the Archer web application recently developed by the Cline Center for Advanced Social Research to collect data on *Xinhua* news articles that mention countries that receive foreign aid from China. We merge country mentions and article sentiment data with information on Chinese bilateral aid allocations compiled by AidData to assess whether coverage of recipients in Chinese media influence where officials target aid. This is an issue that to date has only been considered in democratic contexts. We contribute to this body of research by considering the role of media in an authoritarian context. We plan to have a manuscript ready for submission to a journal by the beginning of the Spring semester and are planning to present our results at the annual meeting of the Midwest Political Science Association this April.

I further have an interest in the politics of multilateral development institutions. I recently coauthored a chapter on the history of and issues related to the World Bank with Matt Winters for the *Handbook of International Organizations: Theories, Concepts and Empirical Insights*. I also have a working paper that explores theoretically and empirically the tension besetting institutions like the World Bank to bend to the interests of their most influential donors versus targeting their loan and grant allocations to the most deserving recipients.

In addition to my interest in foreign aid, I have supported several research collaborations with my methodological expertise and initiated a few lines of methodological research of my own. For instance, in a pair of papers coauthored with Ryan Burge at Eastern Illinois University, we use text-as-data methods to understand political communication in the domain of religion. In an article published in the *Journal of Communication and Religion*, we applied a combination of natural language processing, descriptive analysis, and sentiment analysis to shed new light on the differential political communications of clergy in their sermons on the basis of gender. In another article published in the *Journal of Religion, Media, and Digital Culture*, we explored a novel dataset of Tweets made by more than 80 prominent Protestant Evangelical leaders with an eye to the most common themes in their communications and to their messaging on political issues.

Since May 2020 I have served as an Associate Fellow on the Methods Team at the U.S. Office of Evaluation Sciences (OES). OES is a federal agency that relies on a cross-disciplinary team of social and behavioral scientists to help federal government partners build and use evidence. In my role as methods specialist I have applied my skills to support a wide range of experimental, quasi-experimental, and descriptive research supporting the evaluation and evidence priorities of multiple federal agencies. As a member of the Methods Team, I consult on the development of research designs, support quality control for OES projects by conducting blind reanalyses for evaluations conducted by other team members, and contribute to the development of guidance documents and data visualization tools for OES. I also have played a more direct role in project collaborations and am coauthor on a number of projects that are either being prepared for submission to, or are under review at, peer reviewed journals. This includes rapid evaluation of pandemic relief for small businesses in partnership with the Small Business Administration and evaluation of VA policies aimed at increasing flu vaccine uptake among veterans.

Finally, I have initiated a pair of methodological research programs, one that centers on identifying causal estimates with observational data and another that builds on a theoretically informed estimator for strategic interactions among agents. For the first, I propose a novel application of random forests to the problem of regression adjustment. In addition to developing an R package for implementing this approach to regression adjustment, I detail the method in a working paper that I am preparing for submission to a peer reviewed journal. In the second project, I build upon an existing model-based approach to estimating a "strategic autoregressive model" (StratAM) and currently have a related R package under development for implementing the method.

Beyond my research, I am prepared to teach a range of courses that align with the offerings of the Skalny Center. Such courses include intro to IR, theories of IR, international political economy, and comparative political economy. At Illinois, I have facilitated discussion sections in Intro to Political Science and have served as the instructor of record for an online Intro to International Relations course. Though not courses specifically hosted by the Skalny Center, for the past four years I also have served as a math camp instructor for incoming graduate students entering Illinois' Ph.D. program in political science. Sessions I have taught include linear regression and OLS, probability, calculus, and version control. In my teaching, I promote rigor and expect a strong work-ethic and engagement from my students. At the same time, I believe rigorous demands demand compassion---a much needed virtue in a world where individuals face racial, ethnic, class, gender, and sexual-orientation based forms of discrimination.

In terms of service and activities beyond teaching and research, at Illinois I have taken on various voluntary and elected roles. I have served on, and been interim head of, the graduate Methods Committee. I have also served as an elected member of Illinois' Political Science Graduate Student Association. My capacity as a math camp instructor was voluntary and an act of service for the department I was grateful to provide. I also have served as an organizer for an International Relations workshop for graduate students at Illinois, which provides students an opportunity to share and receive feedback on their ongoing research from peers and faculty members.

Taken together, I believe my experience and qualifications make me well-suited to continuing my research and teaching at Rochester's Skalny Center. Please find the package of application materials that I have included with this letter. You can email or call me any time with questions.

\bigskip

Sincerely,

Miles D. Williams

\vspace{-10pt}

Ph.D. Candidate

\vspace{-10pt}

Department of Political Science

\vspace{-10pt}

University of Illinois at Urbana-Champaign