---
output: 
    stevetemplates::cv
geometry: margin=1in

title: "Cover Letter for GRI at William & Mary"
author: Miles D. Williams

jobtitle: Department of Political Science, University of Illinois at Urbana-Champaign
address: "David Kinley Hall · 1470 W Gregory Drive · Urbana IL, 61801"
email: "milesdw2@illinois.edu"
# github: "milesdwilliams15"
phone: "618-663-9499"
web: "milesdwilliams15.github.io"
fontawesome: yes
updated: false

fontfamily: cochineal
fontsize: 12pt
linkcolor: blue
urlcolor: blue
---

\bigskip

To the Global Research Institute,

\bigskip

I am writing this letter to express my interest in the post-doctoral fellowship focusing on geospatial/economic analysis of Chinese development projects. I am a doctoral candidate in the Department of Political Science at the University of Illinois, and I expect to defend my dissertation by May 2022 under the supervision of Matt Winters, Xinyuan Dai, Bob Pahre, and Rob Carroll. 

My primary research agenda centers on the political economy of foreign aid. I have special interest in identifying the foreign policy goals countries pursue through their aid allocation and in explaining the strategic responses among leading foreign aid donors to each other as they allocate aid to developing countries. To address these issues, I rely on various tools, from formal theory to machine learning, as well as classical econometric techniques.

In my dissertation, I study the issue of strategic interactions among bilateral aid donors. I begin from the assumption that leading industrialized countries target economic assistance to developing countries in order to maximize wide-ranging foreign policy interests. But, as they do so, the aid allocated by one produces a mix of positive and negative foreign policy externalities for all others, and vice versa. 

The first chapter of my dissertation is dedicated to analyzing a game-theoretic model of a political economy of aid. With this model, I gain greater insight into a timely question in international development: *why do donor governments struggle to collaborate in the distribution of foreign aid to developing countries?* Implicit in this question is the presumption that collective provision of aid yields mutual foreign policy gains for donors. However, analysis of the model demonstrates that collective solutions do not always Pareto improve on individual best-responses. The most likely outcome in equilibrium is inefficient competitive waste. Donors direct more of their aid budgets to recipients where rivalry is most pronounced and away from recipients where they share more common interests. Generally, if they could agree to cooperate, a more efficient solution would entail mutually diverting some aid away from recipients that are sites of rival foreign policy gains and to recipients that are sites of mutual interest. However, in many other scenarios the choice between individual and collective optimization can lead to conflicting payoffs between donors. While one donor may do much better under a collective solution, the other will do worse. This highlights a potential source of friction that may explain the stunted progress in donor collaboration to-date.

The remainder of my dissertation deals with empirically identifying *when* and *where* donor governments compete for rival foreign policy gains through aid allocation or pass the buck to others. In doing so, I make a novel contribution to measurement by developing two composite measures that (1) capture leading countries' foreign policy interests with respect to individual developing countries and (2) capture individual developing countries' relative need for economic assistance. Next, using a mix of machine learning and conventional econometric techniques, I recover evidence, not only that leading donor countries engage in strategic responses to one another as they allocate aid but also that their responses are conditioned by their foreign policy interests and by recipient need. Specifically, I find that donor responsiveness is most prevalent within the neediest recipients. Further, among these recipients, donors respond competitively to peer aid where their foreign policy interests are strongest and deferentially to peer aid where their interests are minimal. These findings shed new light on strategic responses among aid donors by revealing not only that donors strategically target their aid based on the giving of others but also by identifying *when* and *where* these responses are competitive or deferential. Following the main empirical analysis I narrow my focus to donor governments' strategic interactions in Southeast Asia. This analysis complements the previous by further clarifying which recipient countries are objects of deference or competition for donors.

My findings have implications for international development policy generally and specifically for progress on addressing global issues that industrialized countries seek to address through foreign aid such as climate change, international migration, and state fragility. Donor governments may pass the buck on these problems that are of mutual interest while they direct more of their resources toward competing for rival material, strategic, and social returns for allocating aid.

Beyond my dissertation, I also maintain a research agenda focused on the determinants and impacts of aid allocation broadly construed. In one paper I was invited to revise and resubmit to *International Studies Quarterly*, I examine how donor interests in supporting bilateral trade, minimizing unwanted migration, and helping a strategically valuable country influence how they differently target economic assistance in developing countries experiencing civil war and those at peace. In another work-in-progress in collaboration with Lucie Lu (University of Illinois), we explore the intersection of aid allocation and media coverage of aid recipients in the context of China's foreign aid program. In this project we rely on the Archer web application recently developed by the Cline Center for Advanced Social Research to collect data on *Xinhua* news articles that mention countries that receive foreign aid from China. We merge country mentions and article sentiment data with information on Chinese bilateral aid allocations compiled by AidData to assess whether coverage of recipients in Chinese media influence where officials target aid or whether China's aid allocations dictate coverage of aid recipients. We plan to have a manuscript ready for submission to a journal by the beginning of the Spring semester.

I further have an interest in the politics of multilateral development institutions. I recently coauthored a chapter on the history of and issues related to the World Bank with Matt Winters for the *Handbook of International Organizations: Theories, Concepts and Empirical Insights*. I also have a working paper that explores theoretically and empirically the tension besetting institutions like the World Bank to bend to the interests of their most influential donors versus targeting their loan and grant allocations to the most deserving recipients.

In addition to my foreign aid research, I also maintain a research agenda centered on political methodology and applications of alternative data sources. With respect to the latter, in a pair of papers coauthored with Ryan Burge at Eastern Illinois University, I use text-as-data methods to understand political communication in the domain of religion. In an article published in the *Journal of Communication and Religion*, we applied a combination of natural language processing, descriptive analysis, and sentiment analysis to shed new light on the differential political communications of clergy in their sermons on the basis of gender. In another article published in the *Journal of Religion, Media, and Digital Culture*, we explored a novel dataset of Tweets made by more than 80 prominent Protestant Evangelical leaders with an eye to the most common themes in their communications and to their messaging on political issues.

My methodological research further extends to developing new methods for identifying causal estimates with observational data. In one ongoing project, I propose a novel application of random forests to the problem of regression adjustment. In addition to developing an R package for implementing this approach to regression adjustment, I detail the method in a manuscript that I will place under review this semester. In another project, I build upon an existing model-based approach to estimating a "strategic autoregressive model" (StratAM) and currently have a related R package under development for implementing the method.

Since May 2020 I have served as an Associate Fellow on the Methods Team at the U.S. Office of Evaluation Sciences (OES). This experience has honed my skills in experimental and quasi-experimental designs and analysis. OES is a federal agency that relies on a cross-disciplinary team of social and behavioral scientists to help federal government partners build and use evidence. In my role on the Methods Team, I consult on the development of research designs, support quality control for OES projects by conducting blind reanalyses for evaluations conducted by other team members, and contribute to the development of guidance documents and data visualization tools for OES. I also have supported rapid evaluation of pandemic relief for small businesses in partnership with the Small Business Administration and several large U.S. metros. This timely and high profile work will develop into multiple manuscripts for publication in highly ranked peer reviewed journals in public policy and administration.

My research and experience has prepared me to teach courses in international relations, political economy, research design, quantitative methods, and formal theory. At Illinois, I have facilitated discussion sections in Intro to Political Science and have served as the instructor of record for an online Intro to International Relations course. For the past four years, I also have served as a math camp instructor for incoming graduate students entering Illinois' Ph.D. program in political science. Sessions I have taught include linear regression and OLS, probability, calculus, and version control. In my teaching, I promote rigor and expect a strong work-ethic and engagement from my students. At the same time, I believe rigorous demands demand compassion---a much needed virtue in a world where individuals face racial, ethnic, class, gender, and sexual-orientation based forms of discrimination.

At Illinois I have taken on various roles and service within the political science department. I have served on, and been interim head of, the graduate Methods Committee. I have also served as an elected member of Illinois' Political Science Graduate Student Association. Further, my capacity as a math camp instructor was voluntary and an act of service for the department I was grateful to provide. I also served as the organizer for an International Relations workshop, which provided graduate students at Illinois an opportunity to share their ongoing research with peers and faculty members to receive feedback and strengthen their work.

These accumulated experiences makes me well suited to the post-doctoral fellowship with the Global Research Institute at William & Mary. In addition to being on track to defend my dissertation before the start date of the fellowship, my primary research agenda centers on the politics of foreign aid. I therefore have a strong interest in making use of AidData's Global Chinese Development Finance Dataset, and I am already using this dataset for some ongoing research that I highlighted above. Methodologically, I have experience with a wide range of tools relevant to this position, including machine learning, parallel computing, and advanced data analytics. While I primarily use R and RStudio for my own research, I regularly collaborate with Python users and am open and willing to developing expertise in the software. Further, while I have less experience with GIS, projects I have collaborated on at OES have involved GIS elements for which I've supported code review and other forms of assistance. 

Beyond the above, I have experience working with a diverse multi-disciplinary team at OES. I also have a growing portfolio of publications and manuscripts. Finally, I have experience teaching a range of courses, from substantive political science courses to statistical methods. I hope to have the opportunity to apply and grow my skill set at GRI. Thank you for your consideration. Please email or call me with questions any time.


\bigskip

Sincerely,

Miles D. Williams

\vspace{-10pt}

Ph.D. Candidate

\vspace{-10pt}

Department of Political Science

\vspace{-10pt}

University of Illinois at Urbana-Champaign