---
output: 
    stevetemplates::cv
geometry: margin=1in

title: "Diversity Statement for Texas Tech University"
author: Miles D. Williams

jobtitle: Department of Political Science, University of Illinois at Urbana-Champaign
address: "David Kinley Hall · 1470 W Gregory Drive · Urbana IL, 61801"
email: "milesdw2@illinois.edu"
# github: "milesdwilliams15"
phone: "618-663-9499"
web: "milesdwilliams15.github.io"
fontawesome: yes
updated: false

fontfamily: cochineal
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---

\vspace*{10mm}
I have enjoyed my share of privileges and endured my share of hardships in life. The former give me the opportunity to recognize and, where I am able, to support inclusivity in work and in life. The latter provide a basis for empathy, for seeing the world and others' circumstances from another perspective than my own. These two factors---opportunity and empathy---are necessary and sufficient for a genuine interest in supporting intellectual and cultural diversity.

I must begin by admitting that I enjoy a station in life that in most respects I do not deserve yet nonetheless have. I am a Ph.D. candidate studying at a fine institution. I am not wealthy, but my spouse and I are able to afford a comfortable life. Though my work at times is a source of stress, I have the unique privilege of serving in a profession that gives me a sense of purpose and is even a source of joy. I get to seek answers to questions that I find interesting and that are important, and I get to educate others about the answers I find. I also am a cisgender white male whose parents, while not rich, owned their own home and tried always to be supportive of my endeavors. These factors provide me certain advantages that I recognize---and many more that I likely still fail to appreciate---that many others are sadly denied.

Being in possession of such privileges comes with an equal measure of responsibilities. As an educator, I am in a position to guide students during a formative period in their lives, to not only teach them something new but also to give them new ways to think. Further, I am in a position to produce knowledge, knowledge that may address societal problems, power, or inequity. Also, I have opportunities to support the work of colleagues who address questions that can seem timeless and weighty beyond what I dare address in my own work. Beyond these, I have resources that I am in a position to steward to the collective good.

The necessity of living up to these responsibilities has been revealed to me by my own struggles---struggles that are certainly not systemic, but that do provide a basis for empathy. During my high school years my family never starved, but we endured significant financial instability as my father struggled to maintain consistent employment. While I had the great blessing to be able to attend a private liberal arts university for my undergraduate education, I often struggled with dark bouts of depression. At the same time that I had the great joy of attending graduate school, completing a master's degree, and going on to begin doctoral studies, my father began a years long and painful struggle with chronic leukemia---a struggle that was ultimately lost two years into my Ph.D. studies. Navigating that loss was difficult, and there were moments I doubted I could continue in my education. Further, only a year before my father's passing, my spouse developed a chronic health condition, one that can be painful and life-threatening if not properly managed. She has now battled this condition for three years and will continue to for the rest of her life.

Dealing with these personal and interpersonal traumas and trials has taught me that no one enters the classroom, their workplace, or their research *only* as a student, a faculty member, or scholar. They enter these tasks as a *whole* person, either feeling light from their victories or heavy from losses. For this reason, scholarship and teaching is necessarily a community exercise, one that is impossible to carry on without the support of colleagues, mentors, and friends. In the midst of the struggles I have faced, I would not enjoy the position I have in life now if not for the support of others. Many suffer from traumas much more severe than my own, and the sources of these traumas come from diverse sources---some interpersonal and others systemic. I hope I can provide future colleagues and students an ounce of the support I have been blessed to receive by continually seeking out ways to educate myself and actively participate in solutions. 

These are issues that Texas Tech values as an institution of higher learning. As a Hispanic Serving Institution and university dedicated to cultural diversity among its faculty and student body, this is a place that not only is aware of the many barriers individuals may face, but also one that actively seeks to address them. That is a mission I wholeheartedly support, and I look forward to the opportunity to contribute to that mission.
